//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Cave_VinsEntities : DbContext
    {
        public Cave_VinsEntities()
            : base("name=Cave_VinsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_APPELLATION_APT> T_APPELLATION_APT { get; set; }
        public DbSet<T_BOUTEILLE_BTL> T_BOUTEILLE_BTL { get; set; }
        public DbSet<T_CHATEAU_CHT> T_CHATEAU_CHT { get; set; }
        public DbSet<T_COULEUR_CLR> T_COULEUR_CLR { get; set; }
        public DbSet<T_FLACONNAGE_FCG> T_FLACONNAGE_FCG { get; set; }
        public DbSet<T_PAYS_PAY> T_PAYS_PAY { get; set; }
        public DbSet<T_REGION_REG> T_REGION_REG { get; set; }
        public DbSet<T_INVENTAIRE_INV> T_INVENTAIRE_INV { get; set; }
        public DbSet<T_EMPLACEMENT_EMP> T_EMPLACEMENT_EMP { get; set; }
        public DbSet<T_LIEU_LIE> T_LIEU_LIE { get; set; }
        public DbSet<T_STOCKAGE_STO> T_STOCKAGE_STO { get; set; }
    
        public virtual ObjectResult<NbBouteillesInEmplacementsFromLieu_Result> NbBouteillesInEmplacementsFromLieu(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NbBouteillesInEmplacementsFromLieu_Result>("NbBouteillesInEmplacementsFromLieu", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NbEmplacementsOQPSaufIdBtl(Nullable<int> idLieu, Nullable<int> idBouteille)
        {
            var idLieuParameter = idLieu.HasValue ?
                new ObjectParameter("idLieu", idLieu) :
                new ObjectParameter("idLieu", typeof(int));
    
            var idBouteilleParameter = idBouteille.HasValue ?
                new ObjectParameter("idBouteille", idBouteille) :
                new ObjectParameter("idBouteille", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NbEmplacementsOQPSaufIdBtl", idLieuParameter, idBouteilleParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NbBouteillesInLieuByIdBtl(Nullable<int> idLieu, Nullable<int> idBouteille)
        {
            var idLieuParameter = idLieu.HasValue ?
                new ObjectParameter("idLieu", idLieu) :
                new ObjectParameter("idLieu", typeof(int));
    
            var idBouteilleParameter = idBouteille.HasValue ?
                new ObjectParameter("idBouteille", idBouteille) :
                new ObjectParameter("idBouteille", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NbBouteillesInLieuByIdBtl", idLieuParameter, idBouteilleParameter);
        }
    }
}
