//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_APPELLATION_APT
    {
        public T_APPELLATION_APT()
        {
            this.T_CHATEAU_CHT = new HashSet<T_CHATEAU_CHT>();
        }
    
        public int APT_I_ID { get; set; }
        public string REG_C_CODE { get; set; }
        public string APT_S_NOM { get; set; }
    
        public virtual T_REGION_REG T_REGION_REG { get; set; }
        public virtual ICollection<T_CHATEAU_CHT> T_CHATEAU_CHT { get; set; }
    }
}
