//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BOUTEILLE_BTL
    {
        public T_BOUTEILLE_BTL()
        {
            this.T_STOCKAGE_STO = new HashSet<T_STOCKAGE_STO>();
        }
    
        public long BTL_I_ID { get; set; }
        public int FCG_I_ID { get; set; }
        public long CHT_I_ID { get; set; }
        public int CLR_I_ID { get; set; }
        public int BTL_I_MILLESIME { get; set; }
        public Nullable<double> BTL_R_PRIXBAS { get; set; }
        public Nullable<double> BTL_R_PRIXHAUT { get; set; }
    
        public virtual T_FLACONNAGE_FCG T_FLACONNAGE_FCG { get; set; }
        public virtual T_COULEUR_CLR T_COULEUR_CLR { get; set; }
        public virtual T_CHATEAU_CHT T_CHATEAU_CHT { get; set; }
        public virtual T_INVENTAIRE_INV T_INVENTAIRE_INV { get; set; }
        public virtual ICollection<T_STOCKAGE_STO> T_STOCKAGE_STO { get; set; }
    }
}
