//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CHATEAU_CHT
    {
        public T_CHATEAU_CHT()
        {
            this.T_BOUTEILLE_BTL = new HashSet<T_BOUTEILLE_BTL>();
        }
    
        public long CHT_I_ID { get; set; }
        public int APT_I_ID { get; set; }
        public string CHT_S_CHATEAU { get; set; }
        public string CHT_T_DESCRIPTION { get; set; }
    
        public virtual T_APPELLATION_APT T_APPELLATION_APT { get; set; }
        public virtual ICollection<T_BOUTEILLE_BTL> T_BOUTEILLE_BTL { get; set; }
    }
}
