//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LIEU_LIE
    {
        public T_LIEU_LIE()
        {
            this.T_EMPLACEMENT_EMP = new HashSet<T_EMPLACEMENT_EMP>();
        }
    
        public long LIE_I_ID { get; set; }
        public string LIE_S_NOM { get; set; }
        public int LIE_I_NBHOR { get; set; }
        public int LIE_I_NBVERT { get; set; }
        public int LIE_I_CAPA { get; set; }
        public string LIE_C_TYPE { get; set; }
        public int LIE_I_NBHEMP { get; set; }
        public int LIE_I_NBVEMP { get; set; }
    
        public virtual ICollection<T_EMPLACEMENT_EMP> T_EMPLACEMENT_EMP { get; set; }
    }
}
