//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAYS_PAY
    {
        public T_PAYS_PAY()
        {
            this.T_REGION_REG = new HashSet<T_REGION_REG>();
        }
    
        public string PAY_C_CODE { get; set; }
        public string PAY_S_NOM { get; set; }
    
        public virtual ICollection<T_REGION_REG> T_REGION_REG { get; set; }
    }
}
