//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGION_REG
    {
        public T_REGION_REG()
        {
            this.T_APPELLATION_APT = new HashSet<T_APPELLATION_APT>();
        }
    
        public string REG_C_CODE { get; set; }
        public string PAY_C_CODE { get; set; }
        public string REG_S_NOM { get; set; }
    
        public virtual ICollection<T_APPELLATION_APT> T_APPELLATION_APT { get; set; }
        public virtual T_PAYS_PAY T_PAYS_PAY { get; set; }
    }
}
