//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaveVins.Entity
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class T_STOCKAGE_STO
    {
        public long STO_I_ID { get; set; }
        public long BTL_I_ID { get; set; }
        public long EMP_I_ID { get; set; }
        public int STO_I_QTE { get; set; }
    
        public virtual T_BOUTEILLE_BTL T_BOUTEILLE_BTL { get; set; }
        public virtual T_EMPLACEMENT_EMP T_EMPLACEMENT_EMP { get; set; }
    }
}
