USE [Cave_Vins]
GO

/****** Object:  Table [dbo].[T_EMPLACEMENT_EMP]    Script Date: 03/03/2013 13:52:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_EMPLACEMENT_EMP](
	[EMP_I_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LIE_I_ID] [bigint] NULL,
	[EMP_I_POSH] [int] NULL,
	[EMP_I_POSV] [int] NULL,
 CONSTRAINT [PK_T_EMPLACEMENT_EMP] PRIMARY KEY CLUSTERED 
(
	[EMP_I_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_EMPLACEMENT_EMP]  WITH CHECK ADD  CONSTRAINT [FK_T_EMPLACEMENT_EMP_T_LIEU_LIE] FOREIGN KEY([LIE_I_ID])
REFERENCES [dbo].[T_LIEU_LIE] ([LIE_I_ID])
GO

ALTER TABLE [dbo].[T_EMPLACEMENT_EMP] CHECK CONSTRAINT [FK_T_EMPLACEMENT_EMP_T_LIEU_LIE]
GO


