USE [Cave_Vins]
GO

/****** Object:  Table [dbo].[T_INVENTAIRE_INV]    Script Date: 01/26/2013 17:22:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_INVENTAIRE_INV](
	[BTL_I_ID] [bigint] NOT NULL,
	[INV_I_NB] [int] NOT NULL,
 CONSTRAINT [PK_T_INVENTAIRE_INV] PRIMARY KEY CLUSTERED 
(
	[BTL_I_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_INVENTAIRE_INV]  WITH CHECK ADD  CONSTRAINT [FK_T_INVENTAIRE_INV_T_BOUTEILLE_BTL] FOREIGN KEY([BTL_I_ID])
REFERENCES [dbo].[T_BOUTEILLE_BTL] ([BTL_I_ID])
GO

ALTER TABLE [dbo].[T_INVENTAIRE_INV] CHECK CONSTRAINT [FK_T_INVENTAIRE_INV_T_BOUTEILLE_BTL]
GO


