USE [Cave_Vins]
GO

/****** Object:  Table [dbo].[T_LIEU_LIE]    Script Date: 03/03/2013 13:44:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_LIEU_LIE](
	[LIE_I_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LIE_S_NOM] [varchar](150) NOT NULL,
	[LIE_I_NBHOR] [int] NOT NULL,
	[LIE_I_NBVERT] [int] NOT NULL,
	[LIE_I_NBHEMP] [int] NOT NULL,
	[LIE_I_NBVEMP] [int] NOT NULL,
	[LIE_I_CAPA] [int] NOT NULL,
	[LIE_C_TYPE] [char](10) NOT NULL,
 CONSTRAINT [PK_T_LIEU_LIE] PRIMARY KEY CLUSTERED 
(
	[LIE_I_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


