USE [Cave_Vins]
GO

/****** Object:  Table [dbo].[T_STOCKAGE_STO]    Script Date: 01/31/2013 21:23:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_STOCKAGE_STO](
	[STO_I_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STO_I_TYPE] [int] NOT NULL,
	[BTL_I_ID] [bigint] NOT NULL,
	[EMP_I_ID] [bigint] NOT NULL,
	[STO_I_QTE] [int] NOT NULL,
	[STO_I_PLACE] [int] NULL,
 CONSTRAINT [PK_T_STOCKAGE_STO] PRIMARY KEY CLUSTERED 
(
	[STO_I_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0 = Stockage de masse, 1 = Stockage unitaire' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'T_STOCKAGE_STO', @level2type=N'COLUMN',@level2name=N'STO_I_TYPE'
GO

ALTER TABLE [dbo].[T_STOCKAGE_STO]  WITH CHECK ADD  CONSTRAINT [FK_T_STOCKAGE_STO_T_BOUTEILLE_BTL] FOREIGN KEY([BTL_I_ID])
REFERENCES [dbo].[T_BOUTEILLE_BTL] ([BTL_I_ID])
GO

ALTER TABLE [dbo].[T_STOCKAGE_STO] CHECK CONSTRAINT [FK_T_STOCKAGE_STO_T_BOUTEILLE_BTL]
GO

ALTER TABLE [dbo].[T_STOCKAGE_STO]  WITH CHECK ADD  CONSTRAINT [FK_T_STOCKAGE_STO_T_EMPLACEMENT_EMP] FOREIGN KEY([EMP_I_ID])
REFERENCES [dbo].[T_EMPLACEMENT_EMP] ([EMP_I_ID])
GO

ALTER TABLE [dbo].[T_STOCKAGE_STO] CHECK CONSTRAINT [FK_T_STOCKAGE_STO_T_EMPLACEMENT_EMP]
GO

